version: '3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: vivalavi/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
      - docs:/app/docs/
    container_name: foodgram_backend
  frontend:
    image: vivalavi/foodgram_frontend
    volumes:
      - static:/frontend_static/
    command: cp -r /app/result_build/. /frontend_static/
  nginx:
    image: vivalavi/foodgram_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - docs:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/