# Generated by Django 4.2.5 on 2023-09-09 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
