# Generated by Django 4.2.5 on 2023-09-08 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique follow",
        ),
    ]
